name: dart_frog_header_auth
description: Header-based authentication middleware for Dart Frog applications.
homepage: https://dartfrog.vgv.dev/
repository: https://github.com/Jesse-Dan/dart_frog_header_auth
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_frog: ^1.0.1
  dart_frog_auth: ^1.1.0
  flutter:
    sdk: flutter
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
